theme: jekyll-theme-minimal
remote_theme: just-the-docs/just-the-docs
title: GuardianTimer Dokumentation
url: "https://tkalippke.github.io"
baseurl: "/GuardianTimerDocs"
description: "Offizielle Dokumentation f√ºr die GuardianTimer iOS Sicherheits-App"
logo: "/assets/images/Logo.png"
color_scheme: default
search_enabled: true
search_button: true
search_heading: "Suche"
heading_anchors: true
back_to_top: true
last_edit: "2026-01-06"
