remote_theme: academicpages/academicpages.github.io
title: GuardianTimer Dokumentation
url: "https://tkalippke.github.io"
baseurl: "/GuardianTimerDocs"
description: "Offizielle Dokumentation f√ºr die GuardianTimer iOS Sicherheits-App"
logo: "/assets/images/Logo.png"
plugins:
  - jekyll-seers
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
collections:
  publications:
    output: true
  talks:
    output: true
  portfolio:
    output: true
  posts:
    permalink: /posts/:year-:month-:day-:title/
    output: true
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"
  -
    scope:
      path: ""
      type: "talks"
    values:
      layout: "talk"
  -
    scope:
      path: ""
      type: "portfolio"
    values:
      layout: "publication"
exclude:
  - Gemfile
  - Gemfile.lock
header_pages:
  - index.md
  - datenschutz.md